version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: my-web-server
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: /home/ubuntu/cod2/Library
        target: /var/www/downloads
      - type: bind
        source: ./downloads.conf
        target: /etc/apache2/conf-available/downloads.conf
    command: bash -c "a2enconf downloads && apache2-foreground"
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: my-mariadb-server
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mariadb_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mariadb_user
      MYSQL_PASSWORD: your_mariadb_user_password
    ports:
      - target: 3306
        published: 3307
        protocol: tcp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    depends_on:
      - db

volumes:
  db_data: {}
