version: "3.9"
services:
  reverse-proxy:
    image: nginx:1.23.4-alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./certs
        target: /etc/letsencrypt
      - type: bind
        source: /home/ubuntu/cod2/servers
        target: /mnt/servers
      - type: bind
        source: ./www
        target: /var/www/html
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./www:/var/www/html
    entrypoint: "/bin/sh"
    command: >
      -c 'trap exit TERM; 
      while :; do
        certbot renew --webroot --webroot-path=/var/www/html --quiet;
        echo "$$(date): Renewal check complete. Next check in 24 hours.";
        sleep 24h & wait $$!;
      done;'
    deploy:
      restart_policy:
        condition: any
        delay: 10s

networks:
  default:
    name: stack_network
    external: true