version: '3.8'

services:
  db:
    image: mariadb:10.11
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - target: 3306
        published: 3307
        protocol: tcp

volumes:
  db_volume: {}

networks:
  default:
    name: stack_network
    external: true