name: cert-init Continuous Integration

on:
  workflow_dispatch:

env:
  WorkingDir: services/cert-init
  StackName: cert-init

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy ${{ env.StackName }}
        working-directory: ${{ env.WorkingDir}}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "Host *
            StrictHostKeyChecking no" > ~/.ssh/config

          ssh-agent bash -c '
            ssh-add ~/.ssh/key
            docker context create temp --docker "host=ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" && docker context use temp

            docker service rm ${{ env.StackName }}_initial-nginx || true
            docker config rm nginx_http_only 2>/dev/null || true
            docker config create nginx_http_only nginx.conf

            LETS_ENCRYPT_EMAIL=${{ secrets.LETS_ENCRYPT_EMAIL }} \
            LETS_ENCRYPT_DOMAINS=${{ vars.LETS_ENCRYPT_DOMAINS }} \
              docker stack deploy -c compose.yml ${{ env.StackName }}
            docker context rm temp -f
          '
   
          rm -f ~/.ssh/key
