name: db Continuous Integration

on:
  push:
    branches: ['**']
    paths:
      - 'services/db/**'
      - '.github/workflows/db.yml'
  workflow_dispatch:

env:
  ComposeFile: services/db/compose.yml
  StackName: db

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy ${{ env.StackName }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "Host *
            StrictHostKeyChecking no" > ~/.ssh/config

          ssh-agent bash -c '
            ssh-add ~/.ssh/key
            docker context create temp --docker "host=ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" && docker context use temp

            DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} \
              docker stack deploy -c ${{ env.ComposeFile }} -d ${{ env.StackName }}
            docker context rm temp -f
          '
   
          rm -f ~/.ssh/key
