name: shutdown-logs Continuous Integration

on:
  push:
    branches: ['**']
    paths:
      - 'services/shutdown-logs/**'
      - '.github/workflows/shutdown-logs.yml'
  workflow_dispatch:

env:
  WorkingDir: services/shutdown-logs
  StackName: shutdown-logs

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy ${{ env.StackName }}
        working-directory: ${{ env.WorkingDir}}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "Host *
            StrictHostKeyChecking no" > ~/.ssh/config

          ssh-agent bash -c '
            ssh-add ~/.ssh/key
            docker context create temp --docker "host=ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" && docker context use temp

            docker config rm shutdown_logs_script_static 2>/dev/null || true
            docker config create shutdown_logs_script_static shutdown_logs.sh

            SHUTDOWN_LOGS_DISCORD_WEBHOOK=${{ secrets.SHUTDOWN_LOGS_DISCORD_WEBHOOK }} \
              docker stack deploy -c compose.yml ${{ env.StackName }}
            docker context rm temp -f
          '
   
          rm -f ~/.ssh/key
